// <auto-generated />
using System;
using BakTraCam.Core.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BakTraCam.Core.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200906203210_bakimciEntity_eklendi_and_bakimentitiy_revize_oldu")]
    partial class bakimciEntity_eklendi_and_bakimentitiy_revize_oldu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("BakTraCam.Core.Entity.BakimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int>("Oncelik")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tBakim");
                });

            modelBuilder.Entity("BakTraCam.Core.Entity.BakimciEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BakimEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BakimEntityId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BakimEntityId");

                    b.HasIndex("BakimEntityId1");

                    b.ToTable("tBakimci");
                });

            modelBuilder.Entity("BakTraCam.Core.Entity.BakimciEntity", b =>
                {
                    b.HasOne("BakTraCam.Core.Entity.BakimEntity", null)
                        .WithMany("Gerceklestirenler")
                        .HasForeignKey("BakimEntityId");

                    b.HasOne("BakTraCam.Core.Entity.BakimEntity", null)
                        .WithMany("Sorumlular")
                        .HasForeignKey("BakimEntityId1");
                });
#pragma warning restore 612, 618
        }
    }
}
